/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewProductRouteImport } from './routes/new-product'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as ServicesRouteRouteImport } from './routes/services/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as TicketsMyTicketsRouteImport } from './routes/tickets/myTickets'
import { Route as TicketsCreateTicketRouteImport } from './routes/tickets/createTicket'
import { Route as ServicesIndexServicesRouteImport } from './routes/services/indexServices'

const NewProductRoute = NewProductRouteImport.update({
  id: '/new-product',
  path: '/new-product',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRouteRoute = ServicesRouteRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsMyTicketsRoute = TicketsMyTicketsRouteImport.update({
  id: '/tickets/myTickets',
  path: '/tickets/myTickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsCreateTicketRoute = TicketsCreateTicketRouteImport.update({
  id: '/tickets/createTicket',
  path: '/tickets/createTicket',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexServicesRoute = ServicesIndexServicesRouteImport.update({
  id: '/indexServices',
  path: '/indexServices',
  getParentRoute: () => ServicesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services': typeof ServicesRouteRouteWithChildren
  '/user': typeof UserRouteRoute
  '/new-product': typeof NewProductRoute
  '/services/indexServices': typeof ServicesIndexServicesRoute
  '/tickets/createTicket': typeof TicketsCreateTicketRoute
  '/tickets/myTickets': typeof TicketsMyTicketsRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services': typeof ServicesRouteRouteWithChildren
  '/user': typeof UserRouteRoute
  '/new-product': typeof NewProductRoute
  '/services/indexServices': typeof ServicesIndexServicesRoute
  '/tickets/createTicket': typeof TicketsCreateTicketRoute
  '/tickets/myTickets': typeof TicketsMyTicketsRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services': typeof ServicesRouteRouteWithChildren
  '/user': typeof UserRouteRoute
  '/new-product': typeof NewProductRoute
  '/services/indexServices': typeof ServicesIndexServicesRoute
  '/tickets/createTicket': typeof TicketsCreateTicketRoute
  '/tickets/myTickets': typeof TicketsMyTicketsRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/services'
    | '/user'
    | '/new-product'
    | '/services/indexServices'
    | '/tickets/createTicket'
    | '/tickets/myTickets'
    | '/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/services'
    | '/user'
    | '/new-product'
    | '/services/indexServices'
    | '/tickets/createTicket'
    | '/tickets/myTickets'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/services'
    | '/user'
    | '/new-product'
    | '/services/indexServices'
    | '/tickets/createTicket'
    | '/tickets/myTickets'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesRouteRoute: typeof ServicesRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRoute
  NewProductRoute: typeof NewProductRoute
  TicketsCreateTicketRoute: typeof TicketsCreateTicketRoute
  TicketsMyTicketsRoute: typeof TicketsMyTicketsRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new-product': {
      id: '/new-product'
      path: '/new-product'
      fullPath: '/new-product'
      preLoaderRoute: typeof NewProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/myTickets': {
      id: '/tickets/myTickets'
      path: '/tickets/myTickets'
      fullPath: '/tickets/myTickets'
      preLoaderRoute: typeof TicketsMyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/createTicket': {
      id: '/tickets/createTicket'
      path: '/tickets/createTicket'
      fullPath: '/tickets/createTicket'
      preLoaderRoute: typeof TicketsCreateTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/indexServices': {
      id: '/services/indexServices'
      path: '/indexServices'
      fullPath: '/services/indexServices'
      preLoaderRoute: typeof ServicesIndexServicesRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
  }
}

interface ServicesRouteRouteChildren {
  ServicesIndexServicesRoute: typeof ServicesIndexServicesRoute
}

const ServicesRouteRouteChildren: ServicesRouteRouteChildren = {
  ServicesIndexServicesRoute: ServicesIndexServicesRoute,
}

const ServicesRouteRouteWithChildren = ServicesRouteRoute._addFileChildren(
  ServicesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesRouteRoute: ServicesRouteRouteWithChildren,
  UserRouteRoute: UserRouteRoute,
  NewProductRoute: NewProductRoute,
  TicketsCreateTicketRoute: TicketsCreateTicketRoute,
  TicketsMyTicketsRoute: TicketsMyTicketsRoute,
  StaffIndexRoute: StaffIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
