/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewProductRouteImport } from './routes/new-product'
import { Route as StaffRouteRouteImport } from './routes/staff/route'
import { Route as ServicesRouteRouteImport } from './routes/services/route'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as TicketsMyTicketsRouteImport } from './routes/tickets/myTickets'
import { Route as TicketsCreateTicketRouteImport } from './routes/tickets/createTicket'
import { Route as ServicesIndexServicesRouteImport } from './routes/services/indexServices'
import { Route as StaffTicketsIndexRouteImport } from './routes/staff/tickets/index'
import { Route as StaffTicketsTicketIdRouteImport } from './routes/staff/tickets/$ticketId'

const NewProductRoute = NewProductRouteImport.update({
  id: '/new-product',
  path: '/new-product',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRouteRoute = ServicesRouteRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRouteRoute,
} as any)
const TicketsMyTicketsRoute = TicketsMyTicketsRouteImport.update({
  id: '/tickets/myTickets',
  path: '/tickets/myTickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsCreateTicketRoute = TicketsCreateTicketRouteImport.update({
  id: '/tickets/createTicket',
  path: '/tickets/createTicket',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexServicesRoute = ServicesIndexServicesRouteImport.update({
  id: '/indexServices',
  path: '/indexServices',
  getParentRoute: () => ServicesRouteRoute,
} as any)
const StaffTicketsIndexRoute = StaffTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffTicketsTicketIdRoute = StaffTicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => StaffRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/services': typeof ServicesRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/new-product': typeof NewProductRoute
  '/services/indexServices': typeof ServicesIndexServicesRoute
  '/tickets/createTicket': typeof TicketsCreateTicketRoute
  '/tickets/myTickets': typeof TicketsMyTicketsRoute
  '/services/': typeof ServicesIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/user': typeof UserIndexRoute
  '/staff/tickets/$ticketId': typeof StaffTicketsTicketIdRoute
  '/staff/tickets': typeof StaffTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/new-product': typeof NewProductRoute
  '/services/indexServices': typeof ServicesIndexServicesRoute
  '/tickets/createTicket': typeof TicketsCreateTicketRoute
  '/tickets/myTickets': typeof TicketsMyTicketsRoute
  '/services': typeof ServicesIndexRoute
  '/staff': typeof StaffIndexRoute
  '/user': typeof UserIndexRoute
  '/staff/tickets/$ticketId': typeof StaffTicketsTicketIdRoute
  '/staff/tickets': typeof StaffTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/services': typeof ServicesRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/new-product': typeof NewProductRoute
  '/services/indexServices': typeof ServicesIndexServicesRoute
  '/tickets/createTicket': typeof TicketsCreateTicketRoute
  '/tickets/myTickets': typeof TicketsMyTicketsRoute
  '/services/': typeof ServicesIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/user/': typeof UserIndexRoute
  '/staff/tickets/$ticketId': typeof StaffTicketsTicketIdRoute
  '/staff/tickets/': typeof StaffTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/services'
    | '/staff'
    | '/new-product'
    | '/services/indexServices'
    | '/tickets/createTicket'
    | '/tickets/myTickets'
    | '/services/'
    | '/staff/'
    | '/user'
    | '/staff/tickets/$ticketId'
    | '/staff/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/new-product'
    | '/services/indexServices'
    | '/tickets/createTicket'
    | '/tickets/myTickets'
    | '/services'
    | '/staff'
    | '/user'
    | '/staff/tickets/$ticketId'
    | '/staff/tickets'
  id:
    | '__root__'
    | '/services'
    | '/staff'
    | '/new-product'
    | '/services/indexServices'
    | '/tickets/createTicket'
    | '/tickets/myTickets'
    | '/services/'
    | '/staff/'
    | '/user/'
    | '/staff/tickets/$ticketId'
    | '/staff/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ServicesRouteRoute: typeof ServicesRouteRouteWithChildren
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  NewProductRoute: typeof NewProductRoute
  TicketsCreateTicketRoute: typeof TicketsCreateTicketRoute
  TicketsMyTicketsRoute: typeof TicketsMyTicketsRoute
  UserIndexRoute: typeof UserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new-product': {
      id: '/new-product'
      path: '/new-product'
      fullPath: '/new-product'
      preLoaderRoute: typeof NewProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/tickets/myTickets': {
      id: '/tickets/myTickets'
      path: '/tickets/myTickets'
      fullPath: '/tickets/myTickets'
      preLoaderRoute: typeof TicketsMyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/createTicket': {
      id: '/tickets/createTicket'
      path: '/tickets/createTicket'
      fullPath: '/tickets/createTicket'
      preLoaderRoute: typeof TicketsCreateTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/indexServices': {
      id: '/services/indexServices'
      path: '/indexServices'
      fullPath: '/services/indexServices'
      preLoaderRoute: typeof ServicesIndexServicesRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/staff/tickets/': {
      id: '/staff/tickets/'
      path: '/tickets'
      fullPath: '/staff/tickets'
      preLoaderRoute: typeof StaffTicketsIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/tickets/$ticketId': {
      id: '/staff/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/staff/tickets/$ticketId'
      preLoaderRoute: typeof StaffTicketsTicketIdRouteImport
      parentRoute: typeof StaffRouteRoute
    }
  }
}

interface ServicesRouteRouteChildren {
  ServicesIndexServicesRoute: typeof ServicesIndexServicesRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteRouteChildren: ServicesRouteRouteChildren = {
  ServicesIndexServicesRoute: ServicesIndexServicesRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteRouteWithChildren = ServicesRouteRoute._addFileChildren(
  ServicesRouteRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffIndexRoute: typeof StaffIndexRoute
  StaffTicketsTicketIdRoute: typeof StaffTicketsTicketIdRoute
  StaffTicketsIndexRoute: typeof StaffTicketsIndexRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffIndexRoute: StaffIndexRoute,
  StaffTicketsTicketIdRoute: StaffTicketsTicketIdRoute,
  StaffTicketsIndexRoute: StaffTicketsIndexRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ServicesRouteRoute: ServicesRouteRouteWithChildren,
  StaffRouteRoute: StaffRouteRouteWithChildren,
  NewProductRoute: NewProductRoute,
  TicketsCreateTicketRoute: TicketsCreateTicketRoute,
  TicketsMyTicketsRoute: TicketsMyTicketsRoute,
  UserIndexRoute: UserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
