FROM node:22-alpine AS build


WORKDIR /app

COPY package.json package-lock.json ./


# Install dependencies
RUN npm install

# Copy source files into application directory
COPY --chown=app:app . /app
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]